
#### PSHB Survey Planner

This app has been designed as a tool to assist with the monitoring and management of the polyphagous shot hole borer (PSHB, *Euwallacea fornicatus*) in Australia. It predicts the best times of the year to conduct PSHB surveys as part of a management plan.

Identifying new PSHB outbreaks early is critical for effective management. PSHB surveillance is conducted using lured traps (to catch beetles flying between trees) and/or inspecting potential host trees for signs of attack. It takes time and resources to detect PSHB when it is present, and continuous survey efforts are not always feasible. 

Survey efforts should be prioritised at times when 1) PSHB is most likely to be detected, and 2) when outbreaks pose the biggest threat of spreading. This occurs when there is a higher abundance of beetles flying to and attacking new trees. This app predicts when beetles will be most abundant, according to weather data.

##### Step 1: Select a location.

Click on the map to select a location. PSHB population growth will be calculated over one year using daily climate data for the location. Daily growth rates are summed over a 30-day window, to give weight to extended periods of high growth.

##### Step 2: Choose a survey type and set your parameters.

The app offers two ways to plan your surveys:

---

**Survey period**

Adjust the total number of weeks in a year during which PSHB surveys can be conducted. The weeks with the highest PSHB growth are highlighted in **<span style="color:lightblue">blue</span>**. These periods (simplified to months in the calendar) are the best times to allocate resources for surveillance.

---

**Multiple surveys**

If your surveillance plan involves a fixed number of discrete surveys spread across the year, select *Multiple surveys* and use the slider to specify how many surveys (1–12) you intend to conduct. The app will find the optimal timing for that number of equally-spaced surveys, maximising the total PSHB activity captured across all survey visits. Optimal survey dates are marked on the growth curve and the corresponding months are highlighted in the calendar grid.

---

NOTE: Predictions are based on 10-year averages (2013–2023) for daily temperature. Actual PSHB activity will vary depending on current climate.<br>


If you found this tool useful, or can think of ways to improve it, please let us know at andrew.coates@curtin.edu.au<br>


This app is built using the temperature-dependent PSHB population model described in:
Coates, A., & Phillips, B. (2026). Boring Beetles and Super Models: Mapping Potential Distributions of a New Invader. *Journal of Biogeography*, *53*(1), e70136. https://doi.org/10.1111/jbi.70136

Code for this app can be accessed at: https://github.com/PopBiolGen/Shiny_PSHB
